// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ostnuphowzvtdebdbnwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zdG51cGhvd3p2dGRlYmRibndvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3OTY5NTQsImV4cCI6MjA2NjM3Mjk1NH0.V6k7MG0bvSP8BkrrVBpCqHtAnt7oDYDDXIaHaEAYme0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);